# MyOTT Subscriptions
development:
  - id: myott
    return_url: http://localhost:3001/subscriptions
    cookie_domain: localhost
    methods:
      - :passwordless

production:
  - id: <%= ENV.fetch("MYOTT_ID", "") %>
    return_url: <%= ENV.fetch("MYOTT_RETURN_URL", "") %>
    cookie_domain: <%= ENV.fetch("MYOTT_COOKIE_DOMAIN", "") %>
    methods:
      - :passwordless
