# MyOTT Subscriptions
development:
  - id: myott
    success_url: http://localhost:3001/subscriptions
    failure_url: http://localhost:3001/subscriptions/invalid
    cookie_domain: localhost
    methods:
      - :passwordless

production:
  - id: <%= ENV.fetch("MYOTT_ID", "") %>
    success_url: <%= URI.join(ENV.fetch("MYOTT_BASE_URL", ""), "/subscriptions").to_s %>
    failure_url: <%= URI.join(ENV.fetch("MYOTT_BASE_URL", ""), "/subscriptions/invalid").to_s %>
    cookie_domain: <%= ENV.fetch("MYOTT_COOKIE_DOMAIN", "") %>
    methods:
      - :passwordless
