# MyOTT Subscriptions
development:
  - id: myott
    success_url: <%= URI.join(ENV["MYOTT_URL"], "/subscriptions").to_s %>
    failure_url: <%= URI.join(ENV["MYOTT_URL"], "/subscriptions/invalid").to_s %>
    methods:
      - :passwordless
  - id: portal
    success_url: <%= URI.join("hub", ENV["PORTAL_URL"], "/").to_s %>
    failure_url: <%= URI.join("hub", ENV["PORTAL_URL"], "/users/invalid").to_s %>
    methods:
      - :passwordless
  - id: admin
    success_url: <%= URI.join("admin", ENV["ADMIN_URL"], "/").to_s %>
    failure_url: <%= URI.join("admin", ENV["ADMIN_URL"], "/users/invalid").to_s %>
    methods:
      - :passwordless

production:
  - id: <%= ENV.fetch("MYOTT_ID", "") %>
    success_url: <%= URI.join(ENV["MYOTT_URL"], "/subscriptions").to_s %>
    failure_url: <%= URI.join(ENV["MYOTT_URL"], "/subscriptions/invalid").to_s %>
    methods:
      - :passwordless
  - id: portal
    success_url: <%= URI.join("hub", ENV["PORTAL_URL"], "/").to_s %>
    failure_url: <%= URI.join("hub", ENV["PORTAL_URL"], "/users/invalid").to_s %>
    methods:
      - :passwordless
  - id: admin
    success_url: <%= URI.join("admin", ENV["ADMIN_URL"], "/").to_s %>
    failure_url: <%= URI.join("admin", ENV["ADMIN_URL"], "/users/invalid").to_s %>
    methods:
      - :passwordless
