name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT: development
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-ECS-Deployments-Role
  SKIP: terraform_docs,actionlint-docker

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - id: ruby-version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> "$GITHUB_OUTPUT"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
          bundler-cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-tflint@main
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: cd terraform/ && terraform init -backend=false -reconfigure
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: bundle exec brakeman

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: ruby-version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> "$GITHUB_OUTPUT"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle exec rspec
